name: maxinsights
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.13
    - ffmpeg=8.0
    - numpy=2.3.2
    - opencv=4.12.0
    - boto3
    - curl
    - jq
    - nomad
    - perl-image-exiftool
    - pytest
    - requests
    - tqdm
    - pip:
          - mcap-protobuf-support==0.5.3
          - mcap==1.3.0
          - typed-ffmpeg==3.6
