name: maxinsights
channels:
    - conda-forge
dependencies:
    - python=3.13
    - opencv=4.12.0
    - numpy=2.3.2
    - tqdm=4.67.1
    - ffmpeg=8.0
    - pytest=8.4.1
    - requests=2.32.5
    - pip=25.2
    - pip:
        - typed-ffmpeg==3.6
